# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query_server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='query_server.proto',
  package='queryserver',
  syntax='proto3',
  serialized_options=_b('\n\023labview.queryserverB\013QueryServerP\001\242\002\004LVQS'),
  serialized_pb=_b('\n\x12query_server.proto\x12\x0bqueryserver\"3\n\rInvokeRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x11\n\tparameter\x18\x02 \x01(\t\" \n\x0eInvokeResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\x1d\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\"0\n\rQueryResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05\"(\n\x13RegistrationRequest\x12\x11\n\teventName\x18\x01 \x01(\t\"B\n\x0bServerEvent\x12\x11\n\teventData\x18\x01 \x01(\t\x12\x10\n\x08serverId\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\x05\x32\xe0\x01\n\x0bQueryServer\x12\x43\n\x06Invoke\x12\x1a.queryserver.InvokeRequest\x1a\x1b.queryserver.InvokeResponse\"\x00\x12@\n\x05Query\x12\x19.queryserver.QueryRequest\x1a\x1a.queryserver.QueryResponse\"\x00\x12J\n\x08Register\x12 .queryserver.RegistrationRequest\x1a\x18.queryserver.ServerEvent\"\x00\x30\x01\x42+\n\x13labview.queryserverB\x0bQueryServerP\x01\xa2\x02\x04LVQSb\x06proto3')
)




_INVOKEREQUEST = _descriptor.Descriptor(
  name='InvokeRequest',
  full_name='queryserver.InvokeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='queryserver.InvokeRequest.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameter', full_name='queryserver.InvokeRequest.parameter', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=86,
)


_INVOKERESPONSE = _descriptor.Descriptor(
  name='InvokeResponse',
  full_name='queryserver.InvokeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='queryserver.InvokeResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=120,
)


_QUERYREQUEST = _descriptor.Descriptor(
  name='QueryRequest',
  full_name='queryserver.QueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='queryserver.QueryRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=151,
)


_QUERYRESPONSE = _descriptor.Descriptor(
  name='QueryResponse',
  full_name='queryserver.QueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='queryserver.QueryResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='queryserver.QueryResponse.status', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=201,
)


_REGISTRATIONREQUEST = _descriptor.Descriptor(
  name='RegistrationRequest',
  full_name='queryserver.RegistrationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eventName', full_name='queryserver.RegistrationRequest.eventName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=243,
)


_SERVEREVENT = _descriptor.Descriptor(
  name='ServerEvent',
  full_name='queryserver.ServerEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eventData', full_name='queryserver.ServerEvent.eventData', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serverId', full_name='queryserver.ServerEvent.serverId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='queryserver.ServerEvent.status', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=311,
)

DESCRIPTOR.message_types_by_name['InvokeRequest'] = _INVOKEREQUEST
DESCRIPTOR.message_types_by_name['InvokeResponse'] = _INVOKERESPONSE
DESCRIPTOR.message_types_by_name['QueryRequest'] = _QUERYREQUEST
DESCRIPTOR.message_types_by_name['QueryResponse'] = _QUERYRESPONSE
DESCRIPTOR.message_types_by_name['RegistrationRequest'] = _REGISTRATIONREQUEST
DESCRIPTOR.message_types_by_name['ServerEvent'] = _SERVEREVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InvokeRequest = _reflection.GeneratedProtocolMessageType('InvokeRequest', (_message.Message,), dict(
  DESCRIPTOR = _INVOKEREQUEST,
  __module__ = 'query_server_pb2'
  # @@protoc_insertion_point(class_scope:queryserver.InvokeRequest)
  ))
_sym_db.RegisterMessage(InvokeRequest)

InvokeResponse = _reflection.GeneratedProtocolMessageType('InvokeResponse', (_message.Message,), dict(
  DESCRIPTOR = _INVOKERESPONSE,
  __module__ = 'query_server_pb2'
  # @@protoc_insertion_point(class_scope:queryserver.InvokeResponse)
  ))
_sym_db.RegisterMessage(InvokeResponse)

QueryRequest = _reflection.GeneratedProtocolMessageType('QueryRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYREQUEST,
  __module__ = 'query_server_pb2'
  # @@protoc_insertion_point(class_scope:queryserver.QueryRequest)
  ))
_sym_db.RegisterMessage(QueryRequest)

QueryResponse = _reflection.GeneratedProtocolMessageType('QueryResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYRESPONSE,
  __module__ = 'query_server_pb2'
  # @@protoc_insertion_point(class_scope:queryserver.QueryResponse)
  ))
_sym_db.RegisterMessage(QueryResponse)

RegistrationRequest = _reflection.GeneratedProtocolMessageType('RegistrationRequest', (_message.Message,), dict(
  DESCRIPTOR = _REGISTRATIONREQUEST,
  __module__ = 'query_server_pb2'
  # @@protoc_insertion_point(class_scope:queryserver.RegistrationRequest)
  ))
_sym_db.RegisterMessage(RegistrationRequest)

ServerEvent = _reflection.GeneratedProtocolMessageType('ServerEvent', (_message.Message,), dict(
  DESCRIPTOR = _SERVEREVENT,
  __module__ = 'query_server_pb2'
  # @@protoc_insertion_point(class_scope:queryserver.ServerEvent)
  ))
_sym_db.RegisterMessage(ServerEvent)


DESCRIPTOR._options = None

_QUERYSERVER = _descriptor.ServiceDescriptor(
  name='QueryServer',
  full_name='queryserver.QueryServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=314,
  serialized_end=538,
  methods=[
  _descriptor.MethodDescriptor(
    name='Invoke',
    full_name='queryserver.QueryServer.Invoke',
    index=0,
    containing_service=None,
    input_type=_INVOKEREQUEST,
    output_type=_INVOKERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='queryserver.QueryServer.Query',
    index=1,
    containing_service=None,
    input_type=_QUERYREQUEST,
    output_type=_QUERYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='queryserver.QueryServer.Register',
    index=2,
    containing_service=None,
    input_type=_REGISTRATIONREQUEST,
    output_type=_SERVEREVENT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_QUERYSERVER)

DESCRIPTOR.services_by_name['QueryServer'] = _QUERYSERVER

# @@protoc_insertion_point(module_scope)
